{"name": "Проверка неуспешного создания существующего пользователя", "status": "passed", "start": 1715753458527, "stop": 1715753459272, "uuid": "6d11f5e0-b8e9-499d-9676-d1b294cfba9b", "historyId": "951e6ee02646ad30d9423b4d2b701b6f", "testCaseId": "951e6ee02646ad30d9423b4d2b701b6f", "fullName": "tests.test_create_user.TestCreateUser#test_error_create_existing_user", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_user"}, {"name": "subSuite", "value": "TestCreateUser"}, {"name": "host", "value": "maksimka"}, {"name": "thread", "value": "34724-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_user"}]}