{"name": "Проверка неуспешного создания существующего пользователя", "status": "passed", "start": 1715753416983, "stop": 1715753417978, "uuid": "a480a379-438a-4d72-8589-1ba26ac5f3c5", "historyId": "951e6ee02646ad30d9423b4d2b701b6f", "testCaseId": "951e6ee02646ad30d9423b4d2b701b6f", "fullName": "tests.test_create_user.TestCreateUser#test_error_create_existing_user", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_user"}, {"name": "subSuite", "value": "TestCreateUser"}, {"name": "host", "value": "maksimka"}, {"name": "thread", "value": "41204-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_user"}]}